language: php

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --no-progress --prefer-dist -o

script:
 - mkdir -p build/logs
 - vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
